apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tweets-to-s3-
spec:
  entrypoint: tweets-to-s3-csv
  templates:
  - name: tweets-to-s3-csv
    container:
      image: chrisadkin/tweets_to_s3_csv:1.1
      command:
      - python
      args:
      - tweets_to_s3_csv.py
      env:
      - name: BEARER_TOKEN
        valueFrom:
          secretKeyRef:
            name: bearer-token
            key: bearertoken
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-access-key-id
            key: awsaccesskeyid
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-secret-access-key
            key: awssecretaccesskey
      - name: ENDPOINT_URL
        value: "http://{{ IP address }}"
      - name: BUCKET
        value: "{{ S3 bucket name }}"
      - name: TWITTER_QUERY
        value: "{{ twitter query }}"
      - name: MAX_TABLE_SIZE
        value: "10"
